#cloud-config

hostname: kairos
k3s:
    enabled: true
stages:
    boot:
        - name: Disable IPv6
          sysctl:
            net.ipv6.conf.all.disable_ipv6: "1"
            net.ipv6.conf.default.disable_ipv6: "1"
        - name: Improve QUIC performance for cloudflared
          sysctl:
            net.core.rmem_max: "5000000"
            net.core.wmem_max: "5000000"
users:
    # Don't change username!
    - name: kairos
      # Generate with openssl passwd (or use plaintext - discouraged)
      passwd: <your password>
      groups:
        - admin
      # Set this to your public key or github user
      ssh_authorized_keys:
        - github:<your github username>

# Additional manifests that are applied by k3s on boot
write_files:
    - path: /var/lib/rancher/k3s/server/manifests/argocd.yaml
      permissions: "0644"
      content: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd
          ---
          apiVersion: helm.cattle.io/v1
          kind: HelmChart
          metadata:
            name: argocd
            namespace: kube-system
          spec:
            chart: argo-cd
            version: 8.0.0
            repo: https://argoproj.github.io/argo-helm
            targetNamespace: argocd
