apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner # Name of the volume.
# The provisioning describes how the volume is provisioned.
provisioning:
    # The disk selector expression.
    diskSelector:
        match: system_disk # The Common Expression Language (CEL) expression to match the disk.
    minSize: 1GiB # The maximum size of the volume, if not specified the volume can grow to the size of the
    grow: true